dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
cache:
  yarn: true
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  - ganache-cli -p 7545
  - truffle compile
  - truffle migrate --network development
  - truffle test
