dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
services: 
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  - truffle compile && ganache-cli -p 7545
  - truffle migrate --network development
  - truffle test
