dist: trusty
sudo: required
language: node_js
node_js:
- '8'
before_install:
- |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
    fi
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs|examples))/' || {
      echo "Only docs were updated, stopping build process."
      exit
    }
install:
- npm install -g truffle
- npm install -g ganache-cli
- npm install
script:
- ganache-cli -p 7545 > /dev/null &
- sleep 5
- truffle compile
- truffle migrate --network development
- truffle test
- truffle migrate --network mainnet
- truffle migrate --network rinkeby
