dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
services: ganache-cli
before-script:
  - ganache-cli -p 7545
script:
  - truffle compile
  - truffle migrate --network development
  - truffle test
